language: node_js
node_js:
  - "5"
sudo: required
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "nohup bash -c 'java -jar WebRTC/test/selenium-server-standalone-2.52.0.jar &'"
  - sleep 3 # give xvfb some time to start
script:
  - "ls"
  - "./initialize.sh"
  - "npm test"
env:
  - XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
services:
  - mongodb
sudo: requireds
